In [14]:
import pandas as pd
import numpy as np

# Carga del archivo
df0 = pd.read_excel('../datas/Option_B/Balance Energetico resumido_DataConsolidada_Brasil_1970_2021_RMFP.xlsx')
df0=df0.applymap(lambda x: round(x, 2) if isinstance(x, (int, float)) else x)

# Imprime las primeras 5 filas de datos para confirmar que se ha leído correctamente
df0.columns
Year= df0["Año"]

In [15]:
df1=pd.read_excel('../datas/Option_B/Summarized enegy balance_Brazil_2021.xlsx', skiprows=range(2),skipfooter=1)
df1.head(12)

,Unnamed: 0,T.S. Oil derivatives,T.S. Coke + T.S. charcoal,T.S. Oil,T.S. Natural gas,T.S. Coal,T.S. Hydroenergy,T.S. Nuclear,T.S. Other primaries,T.S. Electricity,S.T. Firewood,O.T. Sugarcane and products
0,Total supply,133991.003364,11839.951038,93340.783949,36350.921511,15917.208958,31125.011603,3835.74802,28037.316314,58267.370591,26017.951804,49469.742180
1,Charcoal + Coke plants,779.919147,10782.290827,NaN,NaN,7849.840760,NaN,NaN,NaN,NaN,7346.026023,NaN
2,Power plants,4836.062930,NaN,NaN,17485.038361,4405.451064,31125.011603,3835.74802,12826.830566,56285.463934,429.483225,5782.778991
3,Refineries,103076.907340,NaN,93286.201845,2583.619259,NaN,NaN,NaN,5589.695694,NaN,NaN,NaN
4,"Agriculture, fishing and mining",7824.915344,41.587687,NaN,261.076225,146.108629,NaN,NaN,NaN,3998.099243,3149.898631,NaN
5,"Commercial, services, public",729.047766,76.993324,NaN,136.766720,NaN,NaN,NaN,176.906844,11346.641619,81.985163,NaN
6,Industrial,10479.377402,11210.492047,NaN,8417.906755,3497.419671,NaN,NaN,8568.383586,17209.252679,7588.335697,15418.496550
7,Non-energy consumption,13021.030886,NaN,NaN,215.943176,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Residential,6507.294831,411.717118,NaN,454.972960,NaN,NaN,NaN,716.938262,12908.605716,7422.223066,NaN
9,Transport,83101.328411,NaN,NaN,1903.196750,NaN,NaN,NaN,NaN,171.574163,NaN,NaN

In [16]:
df=df0.drop(columns=['Año', 'Unidad'])
columns_1=df1.columns
columns=df.columns

In [17]:
df.columns = columns_1
df.rename(columns={'Unnamed: 0': 'Final Consumption'}, inplace=True)

In [18]:
df.head()

,Final Consumption,T.S. Oil derivatives,T.S. Coke + T.S. charcoal,T.S. Oil,T.S. Natural gas,T.S. Coal,T.S. Hydroenergy,T.S. Nuclear,T.S. Other primaries,T.S. Electricity,S.T. Firewood,O.T. Sugarcane and products
0,Oferta total,24833.79,1869.52,25664.25,180.02,2235.39,3421.52,NaN,223.24,3930.52,31851.53,3600.70
1,Carboneras + Cq. y A.Hornos,375.32,1707.43,NaN,NaN,1483.73,NaN,NaN,NaN,NaN,3493.85,NaN
2,Centrales eléctricas,1184.49,NaN,NaN,NaN,464.09,3421.52,NaN,81.16,3932.24,12.70,88.99
3,Refinerías,24598.32,55.18,25535.85,104.22,158.93,NaN,NaN,NaN,NaN,NaN,NaN
4,"Agro, pesca y minería",403.70,19.37,NaN,NaN,NaN,NaN,NaN,NaN,27.25,4900.69,NaN

In [19]:
rows=df['Final Consumption'].unique()

# Element to drop
element_to_drop = 'Construcción y otros'

# Find the index of the element to drop
index_to_drop = np.where(rows == element_to_drop)[0]

# Drop the element from the array
updated_array = np.delete(rows, index_to_drop)

# Print the updated array
print(updated_array)

['Oferta total' 'Carboneras  + Cq. y A.Hornos' 'Centrales eléctricas'
 'Refinerías' 'Agro, pesca y minería' 'Comercial, servicios, público'
 'Consumo no energético' 'Industrial' 'Residencial' 'Transporte']

In [20]:
df1['Unnamed: 0']

0                       Total supply
1             Charcoal + Coke plants
2                       Power plants
3                         Refineries
4    Agriculture, fishing and mining
5       Commercial, services, public
6                         Industrial
7             Non-energy consumption
8                        Residential
9                          Transport
Name: Unnamed: 0, dtype: object

In [21]:
# Create a dictionary with the mapping between the two columns
mapping = dict(zip(updated_array,df1['Unnamed: 0']))
mapping

# Use the mapping to replace the values in 'Final Consumption' column of df
df['Final Consumption'] = df['Final Consumption'].replace(mapping)

In [ ]:
# Carga del archivo
file_path = '../datas/Option_B/Matriz de balance energético_Brasil_2021.xlsx'

#Dict = pd.read_excel(file_path, sheet_name=None, skiprows=range(4), skipfooter=3)
df_matriz = pd.read_excel(file_path)#, sheet_name=None, skiprows=range(4), skipfooter=3)
df_matriz=df_matriz.applymap(lambda x: round(x, 2) if isinstance(x, (int, float)) else x)

# Imprime las primeras 5 filas de datos para confirmar que se ha leído correctamente
df_matriz.head(29)

In [ ]:
sectores = df_matriz["Consumo Final"].unique()
sectores

In [ ]:
import plotly.graph_objects as go
import numpy as np

# Fuentes de energía (columnas "O.T. ...")
fuentes = ["PETRÓLEO", "GAS NATURAL", 
           "CARBÓN MINERAL", "HIDROENERGÍA", "NUCLEAR",
           "OTRAS PRIMARIAS", "LEÑA", "CAÑA DE AZÚCAR Y DERIVADOS"]

# Sectores de consumo (valores únicos en la columna "Consumo Final")
sectores = df_matriz["Consumo Final"].unique()

# Crear listas para guardar los datos del diagrama de Sankey
labels = list(fuentes) + ['REFINERÍAS', 'DESTILERÍA', 'CARBONERAS + CQ. Y A.HORNOS', 'Producción + Importación'] + list(sectores)
source = []  # índices de las fuentes
target = []  # índices de los destinos
value = []  # valores de los flujos
#print(labels)
# Fuentes que pasan por 'Refinerías', 'Destilerías' y 'Carboneras + Cq. y A.Hornos'
REFINERÍAS = ["PETRÓLEO", "GAS NATURAL", "OTRAS PRIMARIAS"]
DESTILERÍA = ["CAÑA DE AZÚCAR Y DERIVADOS", "OTRAS PRIMARIAS"]
CARBONERAS_CQ_AH = ["LEÑA", "CARBÓN MINERAL"]

# Llenar las listas source, target y value para los nodos de las fuentes a 'Refinerías', 'Destilerías', 'Carboneras + Cq. y A.Hornos' o 'Producción + Importación'
for i, fuente in enumerate(fuentes):
    valor = df_matriz.loc[(df_matriz["Consumo Final"] == "PRODUCCIÓN") | (df_matriz["Consumo Final"] == "IMPORTACIÓN"), fuente].sum()
    print(valor)
    if not np.isnan(valor):  # ignorar los valores NaN
        source.append(i)
        if fuente in REFINERÍAS:
            target.append(len(fuentes))  # el índice del nodo de 'Refinerías'
        elif fuente in DESTILERÍA:
            target.append(len(fuentes) + 1)  # el índice del nodo de 'Destilerías'
        elif fuente in CARBONERAS_CQ_AH:
            target.append(len(fuentes) + 2)  # el índice del nodo de 'Carboneras + Cq. y A.Hornos'
        else:
            target.append(len(fuentes) + 3)  # el índice del nodo de 'Producción + Importación'
        value.append(valor)

# Llenar las listas source, target y value para los nodos de 'Refinerías', 'Destilerías' y 'Carboneras + Cq. y A.Hornos' a 'Producción + Importación'
for i, nodo_intermedio in enumerate(['REFINERÍAS', 'DESTILERÍA', 'CARBONERAS + CQ. Y A.HORNOS'], start=len(fuentes)):
    valor = sum(value[j] for j in range(len(source)) if target[j] == i)
    if not np.isnan(valor):  # ignorar los valores NaN
        source.append(i)
        target.append(len(fuentes) + 3)  # el índice del nodo de 'Producción + Importación'
        value.append(valor)

# Llenar las listas source, target y value para los nodos de 'Producción + Importación' a los sectores
for j, sector in enumerate(sectores):
    if sector not in ['PRODUCCIÓN', 'IMPORTACIÓN']:  # ignorar las filas de 'Producción' e 'Importación'
        valor = df_matriz.loc[df_matriz["Consumo Final"] == sector, fuentes].sum().sum()  # sumar todos los valores para este sector
        if not np.isnan(valor):  # ignorar los valores NaN
            source.append(len(fuentes) + 3)  # el índice del nodo de 'Producción + Importación'
            target.append(len(fuentes) + j + 4)  # los índices de los destinos empiezan después del índice de 'Producción + Importación'
            value.append(valor)

# Crear el diagrama de Sankey
fig = go.Figure(data=[go.Sankey(
    node = dict(
        pad = 15,
        thickness = 20,
        line = dict(color = "black", width = 0.5),
        label = labels,
        color = "blue"
    ),
    link = dict(
        source = source,
        target = target,
        value = value
    )
)])

fig.update_layout(title_text="Flujo de energía en Brasil en 2021", font_size=10)
fig.show()

In [ ]:
print(labels)

In [ ]:
print(value)

In [ ]:
import pandas as pd
import plotly.graph_objects as go

# Your provided DataFrame (replace this with your actual DataFrame)
data = {
    'Sector': ['Total supply', 'Charcoal + Coke plants', 'Power plants', 'Refineries', 'Agriculture, fishing and mining',
               'Commercial, services, public', 'Industrial', 'Non-energy consumption', 'Residential', 'Transport'],
    'T.S. Oil derivatives': [133991.0034, 779.919147, 4836.06293, 103076.9073, 7824.915344, 729.0477664, 10479.3774, 13021.03089, 6507.294831, 83101.32841],
    'T.S. Coke + T.S. charcoal': [11839.95104, 10782.29083, 0, 0, 41.58768666, 76.99332425, 11210.49205, 0, 411.7171183, 0],
    'T.S. Oil': [93340.78395, 0, 17485.03836, 93286.20184, 0, 0, 0, 215.9431763, 454.9729604, 1903.19675],
    'T.S. Natural gas': [36350.92151, 7849.84076, 4405.451064, 2583.619259, 261.0762247, 136.7667205, 8417.906755, 0, 0, 0],
    'T.S. Coal': [15917.20896, 0, 31125.0116, 0, 146.1086291, 0, 3497.419671, 0, 0, 0],
    'T.S. Hydroenergy': [31125.0116, 0, 3835.74802, 5589.695694, 0, 0, 0, 716.9382616, 0, 171.5741634],
    'T.S. Nuclear': [3835.74802, 7346.026023, 12826.83057, 0, 3998.099243, 176.9068438, 8568.383586, 12908.60572, 0, 0],
    'T.S. Other primaries': [28037.31631, 0, 56285.46393, 0, 3149.898631, 11346.64162, 17209.25268, 7422.223066, 0, 0],
    'T.S. Electricity': [58267.37059, 7346.026023, 429.4832245, 0, 0, 81.98516279, 7588.335697, 0, 0, 0],
    'S.T. Firewood': [26017.9518, 0, 5782.778991, 49469.74218, 0, 0, 15418.49655, 0, 0, 0],
    'O.T. Sugarcane and products': [49469.74218, 0, 78.46887779, 0, 0, 0, 0, 0, 0, 0]
}

# Create a DataFrame with the appropriate format for the Sankey diagram
df_sankey = pd.DataFrame(data)

# Create a list of all unique sectors including the Total supply
sectors = df_sankey['Sector'].tolist()

# Initialize lists to store the source, target, and value data for the Sankey diagram
source_indices = []
target_indices = []
values = []

# Loop through the DataFrame to extract the data for the Sankey diagram
for idx, col in enumerate(df_sankey.columns[1:]):
    for i, sector in enumerate(sectors):
        source_indices.append(idx)
        target_indices.append(i)
        values.append(df_sankey[col][i])

# Create the Sankey diagram
fig = go.Figure(data=[go.Sankey(
    node=dict(
        pad=15,
        thickness=20,
        line=dict(color="black", width=0.5),
        label=sectors
    ),
    link=dict(
        source=source_indices,
        target=target_indices,
        value=values
    )
)])

# Customize the layout (optional)
fig.update_layout(
    title_text="Energy Flow in Brazil",
    font=dict(size=10),
)

# Show the Sankey diagram
fig.show()