In [6]:
import pandas as pd
import re
import numpy as np
from collections import defaultdict
import matplotlib.pyplot as plt
import seaborn as sns

path=r'../datas/Option_A/Brazil_Supply and demand series.xlsx'

#path=r'../datas/Option_A/Arg_Brz_Mxc_Supply and demand series.xlsx'

data=pd.read_excel(path)


# Find the index of rows that match a specific expression using regular expressions
regex_pattern = r'^Brazil.*'  # Example regex pattern to match Argentina
indexes = data[data['Unnamed: 0'].str.contains(regex_pattern, regex=True, na=False)].index
indexes=list(indexes)
indexes.append(indexes[-1]+56)
print(indexes)

# Find the List of Items
regex_pattern = r'^Brazil - (.*)'  # Example regex pattern to match Argentina
# Extract the desired part using regular expressions
extracted_list = data.loc[data['Unnamed: 0'].str.contains(regex_pattern, regex=True, na=False), 'Unnamed: 0'].str.extract(regex_pattern, expand=False).to_list()
#print(extracted_list)

Dict=dict()

for i in range(len(extracted_list)):
    Dict[extracted_list[i]]=data[indexes[i]:indexes[i+1]]
    Dict[extracted_list[i]].index.name=None
    Dict[extracted_list[i]]=Dict[extracted_list[i]][1:]
    new_header = Dict[extracted_list[i]].iloc[0] #grab the first row for the header
    #new_header = pd.concat([Dict[extracted_list[i]].iloc[0], Dict[extracted_list[i]].iloc[1]], axis=1).T
    Dict[extracted_list[i]] = Dict[extracted_list[i]][1:] #take the data less the header row
    Dict[extracted_list[i]].columns = new_header #set the header row as the df header 
    Dict[extracted_list[i]] = Dict[extracted_list[i]].reset_index(drop=True)
    Dict[extracted_list[i]]=Dict[extracted_list[i]].iloc[1:]
    Dict[extracted_list[i]]=Dict[extracted_list[i]].iloc[:-1]
    Dict[extracted_list[i]]=Dict[extracted_list[i]].rename(columns={np.nan: 'Year'})
     
    # Round the values of each column to 2 decimal places
    Dict[extracted_list[i]] = Dict[extracted_list[i]].applymap(lambda x: round(x, 2) if pd.notnull(x) and isinstance(x, (int, float)) else x)
    
    
# Set index name to None for each DataFrame in the dictionary Dict
for df in Dict.values():
    df.index.name = None
    df.set_index('Year', inplace=True)
    
activity= extracted_list[0]  
print(f"activity: {activity}\n")

df=Dict[activity]
#df_Production.index.name=None
df.head()

[2, 58, 114, 170, 226, 282, 338, 394, 450, 506, 562, 618, 674, 730, 786, 842, 898, 954, 1010, 1066, 1122, 1178, 1234, 1290, 1346, 1402, 1458, 1514]
activity: Production

/var/folders/cr/7sx_pjr5131byrt21svnsg0w0000gn/T/ipykernel_27446/256634452.py:25: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  extracted_list = data.loc[data['Unnamed: 0'].str.contains(regex_pattern, regex=True, na=False), 'Unnamed: 0'].str.extract(regex_pattern, expand=False).to_list()

3,Oil,Natural gas,Coal,Hydroenergy,Nuclear,Firewood,Sugarcane and products,Other Primary_x000d_\n,Total Primaries,Electricity,...,Kerosene/jet fuel,Diesel oil,Fuel oil,Coke,Charcoal,Gases,Other secondary,Non-energy,Total Secundaries,Total
Year,,,,,,,,,,,,,,,,,,,,,
1970,8161.58,1102.24,1044.43,3421.52,NaN,31851.53,3600.70,223.24,49405.24,3932.24,...,1307.21,5674.61,8399.23,55.18,1766.75,465.95,321.73,886.77,31068.07,49405.24
1971,8521.00,952.80,1108.82,3713.63,NaN,31807.22,3841.81,232.82,50178.10,4435.14,...,1338.29,6065.55,9216.61,49.66,2012.13,466.01,579.44,840.39,33809.63,50178.10
1972,8313.08,909.97,1115.99,4356.82,NaN,32143.13,4298.39,301.43,51438.80,4913.79,...,1391.47,7628.45,10859.63,31.73,2331.77,472.67,512.33,971.51,39563.56,51438.80
1973,8453.46,811.23,1055.34,4976.55,NaN,31897.40,4644.41,310.58,52148.96,5564.30,...,1673.21,8748.11,12913.19,NaN,2474.48,513.83,964.63,971.51,46480.08,52148.96
1974,8969.47,954.48,1457.99,5646.13,NaN,32598.64,4618.65,348.89,54594.25,6163.56,...,1771.39,9661.16,13382.63,NaN,3086.00,526.41,1132.90,1367.85,50398.68,54594.25

In [2]:
print(extracted_list)

['Production', 'Import', 'Export', 'Stock change', 'Unused', 'Total supply', 'Refineries', 'Power plants ', 'Self-producers', 'Gas plants', 'Charcoal plants', 'Coke plants and blast furnaces_x000d_', 'Distilleries', 'Other centers', 'Total transformation', 'Own consumption', 'Losses', 'Adjustment', 'Transport ', 'Industrial', 'Residential', 'Commercial, services, public', 'Agriculture, fishing and mining', 'Construction and others', 'Energy consumption', 'Non-energy consumption', 'Final consumption']

In [4]:
Dict["Production"]["Oil"]+Dict["Import"]["Oil"]-Dict["Export"]["Oil"]

Year
1970     25941.58
1971     28189.22
1972     32968.15
1973     42599.41
1974     43372.32
1975     44154.39
1976     47326.70
1977     48275.82
1978     53718.76
1979          NaN
1980     53505.81
1981     53436.12
1982     53149.13
1983     54247.90
1984          NaN
1985          NaN
1986          NaN
1987          NaN
1988     61053.46
1989          NaN
1990          NaN
1991          NaN
1992          NaN
1993          NaN
1994          NaN
1995     61787.53
1996     70647.23
1997     75201.61
1998          NaN
1999     81705.45
2000     84242.96
2001     83569.23
2002     84401.06
2003     84591.72
2004     87951.51
2005     88556.40
2006     87877.57
2007     90243.06
2008     91294.41
2009     92916.40
2010     92361.20
2011     95868.98
2012     99225.67
2013    106710.28
2014    109658.19
2015    105054.21
2016     96032.99
2017     90901.27
2018     89328.99
2019     91068.38
2020     91833.82
2021     94348.57
Name: Oil, dtype: float64

In [8]:
t_supply=Dict["Production"]+Dict["Import"]-Dict["Export"]

In [ ]:
#sns.barplot(x="Year", y="Oil", data=df,
#            label="Total", color="b")

sns.lineplot(x="Year", y="Oil",data=df, palette="bright", linewidth=2.5)

In [ ]:
# Calculate the number of NaN values in each column
nan_counts = df.isnull().sum()
# Replace NaN values in each column with the desired value (e.g., 0)
for column, count in nan_counts.items():
    if count > 0:
        df[column].fillna(0, inplace=True)
        
df.isnull().sum()

In [ ]:
# Plot all columns against the 'Year' index
df.plot(figsize=(10, 6))
plt.xlabel('Year')
plt.ylabel("ktoe")
plt.title('Evolution of energies Over Time')
plt.legend(loc='upper left')
plt.grid(True)
plt.show()

In [ ]:
df.Oil.plot()

In [12]:
Dict["Total supply"]

t_supply

3,Oil,Natural gas,Coal,Hydroenergy,Nuclear,Firewood,Sugarcane and products,Other Primary_x000d_\n,Total Primaries,Electricity,...,Kerosene/jet fuel,Diesel oil,Fuel oil,Coke,Charcoal,Gases,Other secondary,Non-energy,Total Secundaries,Total
Year,,,,,,,,,,,,,,,,,,,,,
1970,25941.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68543.72,NaN,...,1192.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31085.43,68561.08
1971,28189.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71002.23,NaN,...,1309.60,6122.13,9314.18,NaN,NaN,NaN,NaN,1277.81,34964.93,72157.53
1972,32968.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77377.68,NaN,...,1351.30,NaN,9796.49,NaN,NaN,NaN,NaN,1441.43,39249.79,77063.91
1973,42599.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87525.49,5562.83,...,1622.39,8466.05,11323.55,NaN,NaN,NaN,NaN,1441.43,45447.18,86492.59
1974,43372.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90203.48,6167.08,...,NaN,8835.56,11839.01,NaN,NaN,NaN,NaN,NaN,49213.05,89017.85
1975,44154.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92210.16,6790.51,...,NaN,10162.69,13412.08,NaN,NaN,NaN,NaN,1858.71,54141.28,91042.25
1976,47326.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96121.66,7743.86,...,NaN,11931.35,15233.03,NaN,NaN,NaN,NaN,NaN,59601.48,96789.93
1977,48275.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99740.90,8672.98,...,NaN,12867.54,15453.89,NaN,NaN,NaN,NaN,NaN,61372.26,99627.23
1978,53718.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106117.54,9679.90,...,2149.71,14172.38,16751.73,NaN,NaN,NaN,NaN,NaN,67703.68,105182.91
1979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10891.92,...,NaN,15041.71,17002.66,NaN,NaN,NaN,NaN,NaN,73485.68,115365.02
1980,53505.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113220.26,NaN,...,NaN,16767.67,16909.89,NaN,NaN,NaN,NaN,3145.18,74996.90,113807.10
1981,53436.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113766.16,NaN,...,NaN,16087.47,14062.53,NaN,NaN,NaN,NaN,2543.23,71563.89,111234.78
1982,53149.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116328.01,NaN,...,NaN,15772.91,13666.49,NaN,NaN,NaN,2616.27,2924.13,73421.00,114390.66
1983,54247.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,124340.15,13947.83,...,NaN,15961.90,10043.57,NaN,NaN,NaN,NaN,2617.73,71737.78,119690.40
1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15413.81,...,NaN,16450.01,9435.35,NaN,NaN,NaN,NaN,2910.16,74768.75,127263.27
1985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16814.44,...,2514.11,17038.15,9902.13,NaN,NaN,NaN,NaN,3124.83,80548.88,132420.45
1986,NaN,NaN,8913.26,NaN,NaN,NaN,NaN,NaN,141656.38,18260.81,...,2576.97,19758.97,11003.44,NaN,NaN,NaN,NaN,3282.03,87469.53,138110.98
1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18923.95,...,NaN,20766.43,11123.91,NaN,NaN,NaN,NaN,3142.18,90486.67,143766.48
1988,61053.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146536.48,20020.96,...,2425.38,21101.43,11302.62,NaN,NaN,NaN,NaN,3163.79,92402.90,144780.71
1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20962.20,...,2576.81,21844.48,10518.38,NaN,NaN,NaN,NaN,3030.61,95983.93,146497.62
1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21436.21,...,2370.83,22177.16,9863.17,NaN,NaN,NaN,NaN,3464.12,97884.66,154841.22
1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22475.36,...,2360.42,22870.18,9087.13,NaN,NaN,NaN,NaN,2991.96,98262.82,155976.95
1992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22844.93,...,2261.36,23572.97,9966.64,NaN,NaN,NaN,NaN,3059.32,99839.20,154781.72
1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24029.36,...,2455.18,24273.99,13673.81,NaN,5992.41,NaN,NaN,2636.77,107718.43,161927.60
1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2250.99,25619.44,11768.49,NaN,6073.74,NaN,NaN,3132.67,111256.90,168181.66
1995,61787.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,157672.36,NaN,...,2660.33,26456.88,10451.92,NaN,5597.78,NaN,NaN,3075.48,115607.79,170328.78
1996,70647.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,169567.65,28179.70,...,2879.36,28028.53,12682.67,NaN,NaN,NaN,4728.59,3466.97,122743.90,183425.54
1997,75201.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170770.88,29884.57,...,2831.24,28882.70,13574.93,NaN,4636.11,NaN,5722.87,3874.42,130766.87,184964.52
1998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30973.94,...,3184.17,30165.07,13837.60,NaN,4219.32,NaN,6010.37,4210.23,133730.93,189156.79
1999,81705.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,187993.12,32209.33,...,3273.80,31934.43,12074.99,NaN,4989.54,NaN,7576.67,4139.81,136788.31,199147.37
2000,84242.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193840.19,33805.71,...,3452.05,31949.24,11171.26,NaN,5457.03,NaN,8817.47,4411.84,138632.95,204320.08
2001,83569.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,195894.89,31494.09,...,3825.71,33327.45,10271.20,NaN,4978.94,NaN,9582.93,4188.79,136656.01,203911.15
2002,84401.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,195217.65,32782.89,...,3316.45,32273.55,9842.29,NaN,4867.11,NaN,9119.95,4599.90,139697.62,200469.03
2003,84591.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,203093.48,34484.63,...,2525.45,32399.64,8180.87,NaN,5730.35,NaN,9436.15,3896.04,140285.96,205047.81
2004,87951.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,214954.24,36445.30,...,2462.53,34654.93,6668.60,NaN,6514.45,NaN,9591.74,4195.93,145635.91,214452.53
2005,88556.40,NaN,12523.02,NaN,NaN,NaN,NaN,NaN,221290.44,37912.53,...,2540.67,33892.82,7117.03,6479.20,6423.45,1653.39,9638.56,4533.60,147412.27,220787.78
2006,87877.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,225917.72,39504.82,...,2393.22,34628.34,7060.54,6189.93,6253.23,NaN,10301.46,5196.97,151530.51,226420.34
2007,90243.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,239295.45,41514.39,...,2653.55,36244.33,7857.86,6807.11,NaN,NaN,11294.37,4978.16,161352.17,240886.37
2008,91294.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,251134.83,43350.70,...,2745.37,39347.95,7451.70,7010.50,NaN,1832.52,11431.06,6155.12,168367.66,254807.17
2009,92916.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,244101.33,43392.97,...,2926.94,38536.07,7351.16,NaN,NaN,1724.18,11679.08,5846.93,164259.82,246269.51
2010,92361.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,258785.75,47221.04,...,3449.46,42489.26,6360.19,NaN,NaN,NaN,12254.65,8424.59,182810.19,271406.64
2011,95868.98,NaN,14263.72,NaN,NaN,NaN,NaN,NaN,260746.48,48696.36,...,3764.69,44559.22,5150.30,NaN,NaN,2034.15,13144.81,7337.93,187173.68,275999.03
2012,99225.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,268911.02,51002.58,...,3672.41,48445.94,5223.40,NaN,NaN,1961.77,12951.88,7690.40,195444.89,284356.68
2013,106710.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,284917.42,52477.31,...,3577.58,51713.45,6179.83,NaN,NaN,1903.06,13640.35,7809.97,203395.92,299089.67
2014,109658.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,293358.50,53713.04,...,3650.11,53389.75,8194.85,NaN,NaN,1952.32,13782.14,8344.38,211307.72,309627.80
2015,105054.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,289233.45,52994.98,...,3267.88,50094.65,6436.47,NaN,NaN,1872.98,13159.54,6720.16,201636.06,302242.98
2016,96032.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,276711.56,53161.45,...,3291.40,47576.40,4989.72,NaN,NaN,1805.16,12095.87,6795.44,195243.34,291894.22
2017,90901.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,275417.12,53675.22,...,3306.75,47837.47,4807.26,NaN,NaN,2031.01,12490.16,6469.24,199455.62,296609.73
2018,89328.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,277706.86,54592.56,...,3179.23,48088.50,3377.68,NaN,NaN,2097.50,11278.27,6706.94,196485.88,293447.12
2019,91068.38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,282430.43,55871.62,...,3396.86,49916.91,2920.41,NaN,NaN,1911.91,11677.34,6685.59,200395.12,298805.73
2020,91833.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,283365.33,56060.04,...,1834.97,49929.16,2851.29,NaN,NaN,NaN,10783.07,7094.19,192048.62,290246.50
2021,94348.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,289851.44,58267.37,...,2514.34,53685.05,4727.91,NaN,NaN,NaN,11168.53,6957.56,204133.95,304194.89

In [ ]:
df.Oil

In [ ]:

plt.hist(df.Oil,bins=60)